### ISSUE TITLE
Support for docker-compose version 2

### ISSUE THREAD

**Issue by andreaskoch** [dockito/compose2bash#5]
I just wanted to try compose2bash but it seems that it currently does not support docker-compose files in [version 2](https://docs.docker.com/compose/compose-file/#/versioning):

```
error parsing docker-compose.yml yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `2` into main.Service
```

Do you have any plans on adding support for version 2?

**Comment by maxclaus** [comment]
Could you please provide an example of your docker-compose.yaml file?

**Comment by andreaskoch** [comment]
I guess you can take any example from the docker website (see: [docs.docker.com/compose/compose-file/#version-2](https://docs.docker.com/compose/compose-file/#version-2)) but here is the one I tried to convert with compose2bash:

``` yml
version: '2'

services:
  web:
    image: nginx:1-alpine
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - phpfpm:ro
    networks:
      - front
      - back
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:wambo.co,www.wambo.co"
      - "traefik.protocol=http"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.passHostHeader=true"

  phpfpm:
    image: php:7-fpm-alpine
    volumes:
      - ./web:/var/www/html
    networks:
      - back

networks:
  front:
    driver: bridge
  back:
    driver: bridge
```
